apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: roboshop
  name: ebs-dynamic-pvc
  labels:
    proj: roboshop
    env: dev
    deployment: kubernetes
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-dynamic-sc
  resources:
    requests:
      storage: 10Gi