apiVersion: v1
kind: ConfigMap
metadata:
  namespace: roboshop
  name: catalogue-configmap
  labels:
    proj: roboshop
    env: dev
    deployment: kubernetes
    tier: backend
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"