apiVersion: v1
kind: ConfigMap
metadata:
  namespace: roboshop
  name: {{ .Values.configmap.name }}
  labels:
    app: webservices
    proj: roboshop
    env: dev
    deployment: kubernetes
data:
  index.html: |
    <html>
    <head>
        <title> ROBOSHOP </title>
    </head>
    <body>
        <h1> Welcome to ROBOSHOP </h1>
    </body>
    </html>