apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: dispatch
  labels:
    proj: roboshop
    env: dev
    deployment: kubernetes
    app: dispatch
spec:
  selector:
    proj: roboshop
    env: dev
    deployment: kubernetes
    app: dispatch
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080