apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: {{ .Values.deployment.name }}
  labels:
    proj: roboshop
    env: dev
    deployment: kubernetes
    app: webservices
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      proj: roboshop
      env: dev
      deployment: kubernetes
      app: webservices
  template:
    metadata:
      labels:
        proj: roboshop
        env: dev
        deployment: kubernetes
        app: webservices
    spec:
      containers:
      - name: {{ .Values.deployment.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        volumeMounts:
        - name: "{{ .Values.deployment.name }}-configmap"
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: "{{ .Values.deployment.name }}-data"
          mountPath: /frontend/data
      volumes:
      - name: "{{ .Values.deployment.name }}-data"
        persistentVolumeClaim:
          claimName: efs-dynamic-pvc
      - name: "{{ .Values.deployment.name }}-configmap"
        configMap:
          name: "{{ .Values.configmap.name }}"