apiVersion: v1
kind: ConfigMap
metadata:
  namespace: roboshop
  name: rabbitmq
  labels:
    app: rabbitmq
    proj: roboshop
    env: dev
    deployment: kubernetes
    tier: db   
data:
  RABBITMQ_DEFAULT_USER: roboshop
  RABBITMQ_DEFAULT_PASS: roboshop123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: rabbitmq
  labels:
    app: rabbitmq
    proj: roboshop
    env: dev
    deployment: kubernetes
    tier: db   
spec:
  replicas: 1
  selector:
    matchLabels:
      proj: roboshop
      env: dev
      deployment: kubernetes
      tier: db
  template:
    metadata:
      labels:
        app: rabbitmq
        proj: roboshop
        env: dev
        deployment: kubernetes
        tier: db   
    spec:
      containers:
      - name: rabbitmq
        image: rakeshakuluru/rabbitmq:1.1.1
        imagePullPolicy: Always
        # resources:
        #   requests:
        #     cpu: "100m"
        #     memory: "128Mi"
        #   limits:
        #     cpu: "100m"
        #     memory: "128Mi"
        readinessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5672
          failureThreshold: 2
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: rabbitmq
  labels:
    app: rabbitmq
    proj: roboshop
    env: dev
    deployment: kubernetes
    tier: db
spec:
  selector:
    proj: roboshop
    env: dev
    deployment: kubernetes
    tier: db
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672