apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: roboshop
  name: {{ .Values.statefulset.name}}
  labels:
    proj: roboshop
    env: dev
    deployment: kubernetes
    app: redis
spec:
  replicas: {{ .Values.statefulset.replicas }}
  serviceName: "{{ .Values.statefulset.name }}-headless"
  selector:
    matchLabels:
      proj: roboshop
      env: dev
      deployment: kubernetes
      app: redis
  template:
    metadata:
      labels:
        proj: roboshop
        env: dev
        deployment: kubernetes
        app: redis
    spec:
      containers:
      - name: {{ .Values.statefulset.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.statefulset.containerPort }}
        volumeMounts:
        - name: "{{ .Values.statefulset.name }}-data"
          mountPath: /var/lib/redis
  volumeClaimTemplates:
  - metadata:
      name: "{{ .Values.statefulset.name }}-data"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ebs-dynamic-sc
      resources:
        requests:
          storage: 10Gi