apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-dynamic-sc
  labels:
    proj: roboshop
    env: dev
    deployment: kubernetes
    tier: db
provisioner: ebs.csi.aws.com
parameters:
  type: "gp3"
  fsType: "ext4"
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-dynamic-sc
  labels:
    proj: roboshop
    env: dev
    deployment: kubernetes
    tier: db
provisioner: efs.csi.aws.com
parameters:
  fileSystemId: fs-0c6d73565b2df4059
  directoryPerms: "770"
  basePath: "/roboshop-efs-dynamic"
reclaimPolicy: Retain
volumeBindingMode: Immediate