apiVersion: v1
kind: ConfigMap
metadata:
  namespace: roboshop
  name: rabbitmq-configmap
  labels:
    proj: roboshop
    env: dev
    deployment: kubernetes
    tier: db
data:
  RABBITMQ_DEFAULT_USER: "roboshop"
  RABBITMQ_DEFAULT_PASS: "roboshop123"