apiVersion: v1
kind: Pod
metadata:
  namespace: roboshop
  name: frontend
  labels:
    app: frontend
    project: roboshop
    env: dev
spec:
  containers:
    - name: frontend
      image: rakeshakuluru/frontend:1.1.1
      ports:
        - containerPort: 8080
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80