apiVersion: v1
kind: Pod
metadata:
  namespace: roboshop
  name: frontend
  labels:
    app: frontend
    project: roboshop
    env: dev
spec:
  containers:
    - name: nginx
      image: rakeshakuluru/frontend:1.1.1

    - name: almalinux
      image: almalinux:latest