apiVersion: v1
kind: Pod
metadata:
  # namespace: roboshop
  name: multicontainer-setup
  labels:
    app: frontend
    project: roboshop
    env: dev
spec:
  containers:
    - name: nginx
      image: nginx:latest

    - name: almalinux
      image: almalinux:latest
      command: ["/bin/sleep", "1000"]