apiVersion: v1
kind: Pod
metadata:
  namespace: roboshop
  name: frontend
  labels:
    app: frontend
    proj: roboshop
    env: dev
    deployment: kubernetes
spec:
  containers:
    - name: frontend
      image: nginx:latest