apiVersion: v1
kind: ConfigMap
metadata:
  namespace: roboshop
  name: nginx-config
  labels:
    proj: roboshop
    env: dev
    deployment: kubernetes
# using "data"; this is for environment setup variables for your pod
# you just refer this configmap file in env section under pod
data:
  course: joindevops
  name: siva
  duration: 15hours
  mapping: nginx-config