apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: service-nodeport
  labels:
    proj: roboshop
    env: dev
    deployment: kuberenetes
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    proj: roboshop
    env: dev
    deployment: kubernetes
