apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: service-lb
  labels:
    proj: roboshop
    env: dev
    deployment: kubernetes
spec:
  type: LoadBalancer
  selector:
    proj: roboshop
    env: dev
    deployment: kubernetes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
