apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: deployment
  labels:
    proj: roboshop
    env: dev
    purpose: deployment-poc
spec:  
  replicas: 2
  selector:
    matchLabels:
        app: frontend
        proj: roboshop
        env: dev
        deployment: kubernetes
  template:
    metadata:
      labels:
        app: frontend
        proj: roboshop
        env: dev
        deployment: kubernetes
    spec:
      containers:
        - name: frontend
          image: nginx:1.30.0
          ports:
            - containerPort: 80