apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: mongodb-headless
  labels:
    proj: roboshop
    env: dev
    deployment: kubernetes
    tier: db
spec:
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    tier: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: roboshop
  name: pod-affinity-deployment
  labels:
    proj: roboshop
    env: dev
    deployment: kubernetes
    tier: db
spec:
  replicas: 3
  serviceName: mongodb-headless
  selector:
    matchLabels:
      tier: db
  template:
    metadata:
      labels:
        proj: roboshop
        env: dev
        deployment: kubernetes
        tier: db
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: tier
                  operator: In
                  values:
                  - db
              topologyKey: kubernetes.io/hostname
      containers:
        - name: mongodb
          image: mongo
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"
          volumeMounts:
            - name: data-volume
              mountPath: /data
    volumeClaimTemplates:
     - metadata:
        name: data-volume
        spec:
          storageClassName: "ebs-dynamic-sc"
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 10Gi