apiVersion: v1
kind: ConfigMap
metadata:
  namespace: roboshop
  name: cart-configmap
  labels:
    proj: roboshop
    env: dev
    deployment: kubernetes
    tier: backend
data:
  REDIS_HOST: redis
  CATALOGUE_HOST: catalogue
  CATALOGUE_PORT: "8080"