apiVersion: v1
kind: ConfigMap
metadata:
  namespace: roboshop
  name: debuginstance
  labels:
    app: debug
    proj: roboshop
    env: dev
    deployment: kubernetes
    tier: debug
data:
    MONGO: "TRUE"
    MONGO_URL: "mongodb://mongodb:27017"
    DB_HOST: "mysql-db"
    DB_PORT: "3306"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: deployment
  labels:
    app: deployment
    proj: roboshop
    env: dev
    deployment: kubernetes
    tier: debug
spec:
  replicas: 1
  selector:
    matchLabels:
      proj: roboshop
      env: dev
      deployment: kubernetes
      tier: debug
  template:
    metadata:
      labels:
        app: deployment
        proj: roboshop
        env: dev
        deployment: kubernetes
        tier: debug
    spec:
      containers:
        - name: deployment
          image: rakeshakuluru/debug:1.1.1
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "400m"
              memory: "256Mi"
            limits:
              cpu: "800m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: deploymentservice
  labels:
    app: debugservice
    proj: roboshop
    env: dev
    deployment: kubernetes
    tier: debug
spec:
  selector:
    proj: roboshop
    env: dev
    deployment: kubernetes
    tier: debug
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080