apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: dispatch
  labels:
    proj: roboshop
    env: dev
    deployment: kubernetes
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      proj: roboshop
      env: dev
      deployment: kubernetes
      tier: backend
  template:
    metadata:
      labels:
        proj: roboshop
        env: dev
        deployment: kubernetes
        tier: backend
    spec:
      containers:
      - name: dispatch
        image: rakeshakuluru/dispatch:1.1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: dispatch-data
            mountPath: /dispatch/data
      volumes:
        - name: dispatch-data
          persistentVolumeClaim:
          claimName: efs-dynamic-pvc          
---
apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: dispatch
  labels:
    proj: roboshop
    env: dev
    deployment: kubernetes
    tier: backend
spec:
  selector:
    proj: roboshop
    env: dev
    deployment: kubernetes
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080