deployment:
  name: "testhelm"
  replicas: 1
  container_name: "frontend"
  changeCause: "configuring frontend 1.29.8 using helm"


image:
  # repository: ""
  versionTag: "1.29.8"

service:
  port: 80
  containerPort: 80

configmap:
  name: "testhelm"