apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: mongodb
  labels:
    app: mongodb
    proj: roboshop
    env: dev
    deployment: kubernetes
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      proj: roboshop
      env: dev
      deployment: kubernetes
      tier: db
  template:
    metadata:
      labels:
        app: mongodb
        proj: roboshop
        env: dev
        deployment: kubernetes
        tier: db
    spec:
      containers:
      - name: mongodb
        image: rakeshakuluru/mongodb:1.1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"            
          limits:
            cpu: "400m"
            memory: "512Mi"            
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 27017
        #   failureThreshold: 2
        #   periodSeconds: 10
      #   volumeMounts:
      #   - name: mongodb-storage
      #     mountPath: /data/db
      # volumes:
      # - name: mongodb-storage
      #   persistentVolumeClaim:
      #     claimName: mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: mongodb
  labels:
    app: mongodb
    proj: roboshop
    env: dev
    deployment: kubernetes
    tier: db
spec:
  selector:
    proj: roboshop
    env: dev
    deployment: kubernetes
    tier: db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017