apiVersion: v1
kind: ConfigMap
metadata:
  namespace: roboshop
  name: shipping-configmap
  labels:
    proj: roboshop
    env: dev
    deployment: kubernetes
    tier: backend
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
  DB_PORT: "3306"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: shipping
  labels:
    proj: roboshop
    env: dev
    deployment: kubernetes
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      proj: roboshop
      env: dev
      deployment: kubernetes
      tier: backend
  template:
    metadata:
      labels:
        proj: roboshop
        env: dev
        deployment: kubernetes
        tier: backend
    spec:
      containers:
      - name: shipping
        image: rakeshakuluru/shipping:1.1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: shipping-configmap
        env:
          - name: DB_PASS
            value: "roboshop@1"
---
apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: shipping
  labels:
    proj: roboshop
    env: dev
    deployment: kubernetes
    tier: backend
spec:
  selector:
    proj: roboshop
    env: dev
    deployment: kubernetes
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080